# conda env create -f environment.yml
# This is a legacy file. We recommend using uv for development:
#   pip install uv
#   uv pip install -e ".[dev]"
name: lume-dev
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pip
  - pip:
    - -e .[dev]
